VERBOSE=true
#for Wi-Fi connection
NETWORK_DEVICE="wlan0"
NETWORK_NAME="SKOLTECH_5G"
#Leave empty if no login is needed
NETWORK_LOGIN="George.Rafaelyan@skoltech.ru"
BOOT_SIZE="1G"
#if no SWAP size then SWAP_SIZE=RAM+2GB
SWAP_SIZE=""
SYS_SIZE="1.3T"
CHROOT_SCRIPT="./arch_chroot_script.sh"
DEFAULT_GROUP="untrusted"
SUDO_GROUP="admins"
HOSTNAME="genjoyers"
TIMEZONE="Europe/Russia"
