VERBOSE=true
DEVICE="wlan0"
NETWORK="Xiaomi 12"
#it is expected that the first disk will have both boot and SWAP partitions
DISKS=("/dev/sda")
BOOT_SIZE="1G"
#if no SWAP size then SWAP_SIZE=RAM+2GB
SWAP_SIZE=""
HOSTNAME="arch-server"
TIMEZONE="Europe/Russia"
